#!/usr/bin/env python
# -*- coding: utf-8 -*-

from betlib.models.team import add_team_alias
from betlib.mongo import get_db

client = get_db("prono", mongolab=True)

aliases = {
    "Manchester City": "Man City",
    "West Ham United": "West Ham",
    "Blackburn Rovers": "Blackburn",
    "Tottenham Hotspur": "Tottenham",
    "Wigan Athletic": "Wigan",
    "Birmingham City": "Birmingham",
    "Newcastle United": "Newcastle",
    "Stoke City": "Stoke",
    "West Bromwich Albion": "West Brom",
    "Manchester United": "Man United",
    "Bolton Wanderers": "Bolton",
    "Wolverhampton Wanderers": "Wolves",
    "Queens Park Rangers": "QPR",
    "Cardiff City": "Cardiff",
    "Hull City": "Hull",
    "Swansea City": "Swansea",
    "Norwich City": "Norwich",
    "Leicester City": "Leicester",
    "PSG": "Paris SG",
    "PSG": "Paris Saint Germain",
    "Olympique Lyonnais": "Lyon",
    "Olympique Marseille": "Marseille",
     u"Saint-Étienne": "St Etienne",
     u"Saint-Étienne": "ASSE",
    "Evian TG": "Evian Thonon Gaillard",
    "Derby County": "Derby",
    "Mainz 05": 'Mainz',
    "Hannovre 96": 'Hannover',
    "Wolfsbourg": 'Wolfsburg',
    "Borussia M'gladbach" : "M'gladbach",
    "Bayer Leverkusen": 'Leverkusen',
    "Borussia Dortmund": 'Dortmund',
    "Augsbourg": 'Augsburg',
    "Hertha BSC": 'Hertha',
    "Hertha BSC": 'Hertha Berlin',
    "Eintracht Francfort": 'Ein Frankfurt',
    "Hambourg SV": 'Hamburg',
    "Fribourg": 'Freiburg',
    "Cologne": 'FC Koln',
    "Werder Brême": "Werder Bremen",
    "Nuremberg": 'Nurnberg',
    "Eintracht Brunswick": 'Braunschweig',
    "Fortuna Düsseldorf": 'Fortuna Dusseldorf',
    "Greuther Fürth": 'Greuther Furth',
    "St. Pauli": "St Pauli",
    "Energie Cottbus": 'Cottbus',
    "Arminia Bielefeld": 'Bielefeld',
    "Karlsruher SC": 'Karlsruhe',
    "MSV Duisbourg": "Duisburg",
    "Alemannia Aachen": "Aachen",
    "1860 Munich": "Munich 1860",
    "Real Betis": "Betis",
    "Real Santander": "Santander",
    "Deportivo Xerez": "Xerez",
    "Real Saragosse": "Zaragoza",
    "Atlético Madrid": "Atl. Madrid",
    "Real Valladolid": "Valladolid",
    "Sporting Gijón": "Gijon",
    "Grenade 74 CF": "Granada CF",
    "Deportivo La Corogne": "Dep. La Coruna",
    "Cadix": "Cadiz",
    "Real Murcie": "Murcia",
    "Deportivo Alavés": "Alaves",
    "Athletic Club": "Ath Bilbao",
    "Almería": "Almeria",
    "Schalke 04": "Schalke",
    "Fortuna Düsseldorf": "Dusseldorf",
    "Borussia M'gladbach": "B. Monchengladbach",
    "Cologne": "Köln",
    "Hambourg SV": "Hamburger",
    "Hambourg SV": "Hamburger SV",
    "Stuttgart": "VfB Stuttgart",
    "Karlsruher SC": "Karlsruher",
    "Newcastle United": "Newcastle Utd",
    "Sheffield United": "Sheffield Utd",
    "Leeds United": "Leeds",
    "Charlton Athletic": "Charlton",
    "ADO Den Haag": "Den Haag",
    "RKC Waalwijk": "Waalwijk",
    "FC Emmen": "Emmen",
    "FC Omniworld": "Almere City",
    "Go Ahead Eagles": "G.A. Eagles",
    "RBC": "Roosendaal",
    "De Graafschap": "Graafschap",
    "PEC Zwolle": "Zwolle",
    "NAC Breda": "Breda",
    "AGOVV Apeldoorn": "Apeldoorn",
    "Helmond Sport": "Helmond",
    "VVV": "Venlo",
    "BV Veendam": "Veendam",
    "Roda JC": "Roda",
    "TOP Oss": "Oss",
    "MVV": "Maastricht",
    "NEC": "Nijmegen",
    "FC Eindhoven": "Eindhoven FC",
}

for team_name in aliases:
    add_team_alias(team_name, aliases[team_name], client)
